name = "edgevector-db"
main = "src/index.ts"
compatibility_date = "2024-10-14"
compatibility_flags = ["nodejs_compat"]

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "edgevector-db"
database_id = "placeholder-id"  # Will be replaced after creating database

# Durable Objects
[[durable_objects.bindings]]
name = "SHARD_MANAGER"
class_name = "ShardManager"

[[durable_objects.bindings]]
name = "QUERY_PATTERN_ANALYZER"
class_name = "QueryPatternAnalyzer"

[[durable_objects.bindings]]
name = "SSE_MANAGER"
class_name = "SSEManager"

# Migrations directory
[[migrations]]
tag = "v1"
new_sqlite_classes = ["ShardManager", "QueryPatternAnalyzer", "SSEManager"]

# KV Namespaces
[[kv_namespaces]]
binding = "CACHE"
id = "placeholder-cache-id"

[[kv_namespaces]]
binding = "METADATA"
id = "placeholder-metadata-id"

# R2 Buckets (for cold storage)
[[r2_buckets]]
binding = "COLD_STORAGE"
bucket_name = "edgevector-cold-storage"

# Workers AI binding
[ai]
binding = "AI"

# Environment variables
[vars]
ENVIRONMENT = "development"

# Production environment
[env.production]
name = "edgevector-db-production"
vars = { ENVIRONMENT = "production" }

# Staging environment
[env.staging]
name = "edgevector-db-staging"
vars = { ENVIRONMENT = "staging" }
